const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const t=(key,params)=>window.I18n.t(key,params);
const localMonthValue=()=>{const today=new Date();return `${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}`};
const state={csrf:'',profile:null,accounts:[],archivedAccounts:[],categories:[],transactions:[],alerts:[],month:new Date().toISOString().slice(0,7),importPreview:null,statisticsMonth:localMonthValue(),statisticsBreakdownPeriod:1,statisticsRenderedMonth:localMonthValue(),statisticsRenderedPeriod:1,statisticsTrendThrough:localMonthValue(),statisticsTrend:[],statisticsBreakdownRequest:0,statisticsTrendRequest:0};
const locale=()=>window.I18n.language==='en'?'en-US':'vi-VN';
const money=v=>`${new Intl.NumberFormat(locale()).format(Number(v||0))} ₫`,dateVi=v=>v?new Intl.DateTimeFormat(locale()).format(new Date(`${v.slice(0,10)}T00:00:00`)):'—';
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const finiteNumber=value=>{const number=Number(value);return Number.isFinite(number)?number:0};
const statisticsMonthPattern=/^(\d{4})-(0[1-9]|1[0-2])$/;
function formatStatisticsMonth(value){const match=statisticsMonthPattern.exec(value);return match?new Intl.DateTimeFormat(locale(),{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(Number(match[1]),Number(match[2])-1,1))):'—'}
function statisticsDateRange(endMonth,period){const match=statisticsMonthPattern.exec(endMonth);if(!match||![1,3,6,12].includes(period))return null;const year=Number(match[1]),month=Number(match[2]),startDate=new Date(Date.UTC(year,month-period,1)),startMonth=`${startDate.getUTCFullYear()}-${String(startDate.getUTCMonth()+1).padStart(2,'0')}`,lastDay=new Date(Date.UTC(year,month,0)).getUTCDate();return{dateFrom:`${startMonth}-01`,dateTo:`${endMonth}-${lastDay}`,label:period===1?formatStatisticsMonth(endMonth):`${formatStatisticsMonth(startMonth)} – ${formatStatisticsMonth(endMonth)}`}}
const category=id=>state.categories.find(x=>x.id===Number(id)),account=id=>state.accounts.find(x=>x.id===Number(id))||state.archivedAccounts.find(x=>x.id===Number(id));
const systemCategoryTranslationKeys=Object.freeze({'Thu nhập':'category_income','Nhà ở':'category_housing','Điện nước':'category_utilities','Ăn uống':'category_dining','Mua sắm':'category_shopping','Di chuyển':'category_transportation','Y tế':'category_healthcare','Học tập':'category_education','Viễn thông':'category_telecommunications','Chuyển khoản':'category_transfer','Khác':'category_other','Học phí':'category_tuition','Nhiên liệu':'category_fuel','Uncategorised':'uncategorized'});
function displayCategoryName(item){const fallback=String(item?.name||t('generic_category'));if(!item||item.custom!==false)return fallback;const key=systemCategoryTranslationKeys[fallback];return key?t(key):fallback}
function displayCategoryText(name){const fallback=String(name||t('uncategorized')),key=systemCategoryTranslationKeys[fallback];return key?t(key):fallback}
function alertCopy(item){if(window.I18n.language!=='en')return{explanation:item.explanation,action:item.suggested_action};if(item.kind==='BURN_RATE')return{explanation:t('burn_rate_explanation'),action:t('burn_rate_action')};return{explanation:t(item.severity==='CRITICAL'?'threshold_critical_explanation':'threshold_warning_explanation'),action:t('threshold_action')}}
const accountName=x=>x?`${x.name}${x.last_four?` •••• ${x.last_four}`:''}`:t('accounts');
const templateName=item=>window.I18n.language==='en'&&['VCB','TCB','MB'].includes(item.bank_code)?t(`template_${item.bank_code.toLowerCase()}`):item.name;
class ApiError extends Error{constructor(message,status){super(message);this.status=status}}
const serverMessage=()=>window.I18n.language==='en'?'Cannot reach the API. Start Flask and open http://127.0.0.1:5000.':'Không kết nối được API. Hãy chạy Flask và mở http://127.0.0.1:5000.';
async function responseData(response){const type=response.headers.get('content-type')||'',body=await response.text();if(type.includes('json')){try{return body?JSON.parse(body):{}}catch{throw new ApiError(`${t('request_failed')}: ${t('invalid_json')}`,response.status)}}if(type.includes('text/html')||body.trimStart().toLowerCase().startsWith('<!doctype'))throw new ApiError(serverMessage(),response.status);return body}
async function getCsrf(){const r=await fetch('/auth/csrf',{credentials:'same-origin'}),d=await responseData(r);if(!r.ok)throw new ApiError(d?.error||`${t('request_failed')} (${r.status})`,r.status);if(!d.csrf_token)throw new ApiError(serverMessage(),r.status);state.csrf=d.csrf_token}
async function api(path,options={}){const method=options.method||'GET';if(method!=='GET'&&!state.csrf)await getCsrf();const headers=new Headers(options.headers||{});if(method!=='GET')headers.set('X-CSRFToken',state.csrf);if(options.body&&!(options.body instanceof FormData))headers.set('Content-Type','application/json');const r=await fetch(path,{...options,method,headers,credentials:'same-origin'});if(r.status===401){showAuth();throw new ApiError(t('session_expired'),401)}const data=await responseData(r);if(!r.ok)throw new ApiError(data?.error||`${t('request_failed')} (${r.status})`,r.status);return data}
function showAuth(mode='login'){$('#auth-screen').classList.remove('hidden');$('#app-shell').classList.add('hidden');$('#login-form').classList.toggle('hidden',mode!=='login');$('#register-form').classList.toggle('hidden',mode!=='register')}
function showApp(){$('#auth-screen').classList.add('hidden');$('#app-shell').classList.remove('hidden')}
function toast(title=t('updated'),detail=''){const element=$('#toast');$('b',element).textContent=title;$('small',element).textContent=detail;element.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>element.classList.remove('show'),3000)}
function busy(b,on,label=t('loading')){if(!b)return;if(!b.dataset.labelVi)b.dataset.labelVi=b.textContent;b.disabled=on;b.textContent=on?label:(b.dataset.i18nBusyKey?t(b.dataset.i18nBusyKey):b.dataset.labelVi)}
function formError(f,e=''){$('.form-error',f).textContent=e}
async function bootstrap(){try{state.profile=await api('/profile');showApp();$('.profile-mini b').textContent=state.profile.full_name;$('.profile-mini small').textContent=state.profile.email.replace(/^(.{2}).*(@.*)$/,'$1***$2');$('.welcome-row h1').innerHTML=`${esc(t('greeting_named',{name:state.profile.full_name}))} <span>👋</span>`;await Promise.all([loadAccounts(),loadCategories()]);populateSelects();await Promise.all([loadDashboard(),loadTransactions(),loadBudgets(),loadAlerts(),loadStatistics(),loadTemplates()])}catch(e){if(e.status!==401)toast(t('init_failed'),e.message)}}
async function loadAccounts(){const items=(await api('/accounts')).items;state.accounts=items.filter(x=>!x.archived);state.archivedAccounts=items.filter(x=>x.archived);renderAccounts()}
async function loadCategories(){state.categories=(await api('/categories')).items.filter(x=>x.nature)}
async function loadTemplates(){const items=(await api('/imports/templates')).items;$('#import-template').innerHTML=items.length?items.map(x=>`<option value="${x.id}">${esc(x.bank_code)} — ${esc(templateName(x))}</option>`).join(''):`<option value="">${t('no_template')}</option>`}
function populateSelects(){const opts=state.accounts.map(x=>`<option value="${x.id}">${esc(accountName(x))}</option>`).join('');$('#transaction-account').innerHTML=`<option value="">${t('all_accounts')}</option>${opts}`;$('#import-account').innerHTML=opts||`<option value="">${t('create_account_first_option')}</option>`;$('[name="account_id"]',$('#transaction-form')).innerHTML=opts;$('[name="category_id"]',$('#transaction-form')).innerHTML=state.categories.map(x=>`<option value="${x.id}">${esc(displayCategoryName(x))}</option>`).join('')}
async function loadDashboard(){const d=await api(`/statistics/dashboard?month=${state.month}`),metrics=[['↗','mint',t('income'),money(d.income),t('recorded_income')],['↘','coral',t('expense'),money(d.expense),t('recorded_expense')],['◇','blue',t('safe_to_spend'),money(d.safe_to_spend),t('after_commitments')],['◎','violet',t('net_cashflow'),money(d.net),t(d.net>=0?'positive_cashflow':'negative_cashflow')]];$('#dashboard-metrics').innerHTML=metrics.map((x,i)=>`<article class="metric-card ${i===0?'accent':''}"><div class="metric-head"><span class="metric-icon ${x[1]}">${x[0]}</span></div><p>${x[2]}</p><strong>${x[3]}</strong><small>${x[4]}</small></article>`).join('');$('#dashboard-budgets').innerHTML=budgetRows(d.budget_progress)}
function budgetRows(items){return items.length?items.map(x=>{const tone=x.status==='RED'?'danger':x.status==='AMBER'?'warning':'good',label=x.status==='RED'?t('over_budget'):x.status==='AMBER'?t('near_budget'):t('on_track'),item=category(x.category_id),name=item?displayCategoryName(item):String(x.category||t('generic_category'));return `<div class="budget-row"><span class="cat-icon ${tone==='danger'?'shop':tone==='warning'?'food':'travel'}">${esc(name[0]||'?')}</span><div><b>${esc(name)}</b><small>${money(x.spent)} / ${money(x.budget)}</small><div class="progress"><i class="${tone}" style="width:${Math.min(x.percent,100)}%"></i></div></div><strong class="status ${tone}-text">${x.percent}%<small>${label}</small></strong></div>`}).join(''):empty(t('no_budget_month'),t('set_limit_hint'))}
const empty=(title,text)=>`<div class="empty-state"><b>${title}</b><span>${text}</span></div>`;
async function loadTransactions(page=1){const month=$('#transaction-month').value||state.month,[y,m]=month.split('-').map(Number),last=new Date(y,m,0).getDate(),p=new URLSearchParams({page,per_page:20,date_from:`${month}-01`,date_to:`${month}-${last}`});if($('#transaction-account').value)p.set('account_id',$('#transaction-account').value);if($('#transaction-direction').value)p.set('direction',$('#transaction-direction').value);const d=await api(`/transactions?${p}`);state.transactions=d.items;renderTransactions(d);$('#recent-transactions').innerHTML=transactionRows(d.items.slice(0,5),false)}
function transactionRows(items,controls=true){return items.length?items.map(x=>`<tr>${controls?'<td><input type="checkbox"></td>':''}<td><span class="merchant-logo ${x.direction==='IN'?'green':''}">${x.direction==='IN'?'↗':'↘'}</span><b>${esc(x.description||t('no_description'))}</b></td><td><span class="tag">${esc(displayCategoryName(category(x.category_id)))}</span></td><td>${esc(accountName(account(x.account_id)))}</td><td>${dateVi(x.date)}</td><td class="amount ${x.direction==='IN'?'in':'out'}">${x.direction==='IN'?'+':'−'} ${money(x.amount)}</td>${controls?`<td><button class="row-menu" data-delete-transaction="${x.id}">×</button></td>`:''}</tr>`).join(''):`<tr><td colspan="${controls?7:5}">${empty(t('no_transactions'),t('add_first_transaction'))}</td></tr>`}
function renderTransactions(d){const q=$('#transaction-search').value.toLowerCase(),items=d.items.filter(x=>(x.description||'').toLowerCase().includes(q));$('#transaction-rows').innerHTML=transactionRows(items);$('.pagination>span').textContent=t('transaction_count',{total:d.total,page:d.page,pages:Math.max(d.pages,1)});$('.pagination>div').innerHTML=`<button data-page="${Math.max(1,d.page-1)}" ${d.page<=1?'disabled':''}>‹</button><button class="active">${d.page}</button><button data-page="${Math.min(d.pages,d.page+1)}" ${d.page>=d.pages?'disabled':''}>›</button>`}
async function loadBudgets(){const [b,d]=await Promise.all([api(`/budgets?month=${state.month}`),api(`/statistics/dashboard?month=${state.month}`)]),total=b.items.reduce((s,x)=>s+x.amount,0),spent=d.expense,summary=$$('.budget-summary>div:not(.ring) strong');summary[0].textContent=money(total);summary[1].textContent=money(spent);summary[2].textContent=money(total-spent);const pct=total?Math.round(spent/total*100):0;$('.ring').style.setProperty('--value',Math.min(pct,100));$('.ring b').textContent=`${pct}%`;const progress=Object.fromEntries(d.budget_progress.map(x=>[x.category_id,x]));$('#budget-cards').innerHTML=b.items.length?b.items.map(x=>{const c=category(x.category_id),name=displayCategoryName(c),p=progress[x.category_id]||{spent:0,percent:0,status:'GREEN'},tone=p.status==='RED'?'danger':p.status==='AMBER'?'warning':'good',label=p.status==='RED'?t('over_budget'):p.status==='AMBER'?t('near_budget'):t('on_track');return `<article class="category-card ${tone==='danger'?'danger-border':''}"><div><span class="cat-icon food">${esc(name[0]||'?')}</span><span><b>${esc(name)}</b><small>${natureLabel(c?.nature)}</small></span><button data-edit-budget="${x.category_id}">✎</button></div><strong>${money(p.spent)} <small>/ ${money(x.amount)}</small></strong><div class="progress large"><i class="${tone}" style="width:${Math.min(p.percent,100)}%"></i></div><p><span class="${tone}-text">${label}</span><span>${p.percent}%</span></p></article>`}).join(''):empty(t('no_budget'),t('add_budget_hint'))}
const natureLabel=n=>({COMMITTED:t('committed'),SEMI_FIXED:t('semi_fixed'),DISCRETIONARY:t('discretionary')}[n]||t('generic_category'));
async function loadAlerts(filter='ALL'){state.alerts=(await api('/alerts')).items;const unread=state.alerts.filter(x=>x.status==='UNREAD').length,hasUnread=unread>0;$('#alert-total').textContent=state.alerts.length;$('#alert-unread').textContent=unread;$('.nav-badge').textContent=unread;$('.nav-badge').classList.toggle('hidden',!hasUnread);const items=filter==='ALL'?state.alerts:state.alerts.filter(x=>x.status===filter);$('#alert-inbox').innerHTML=items.length?items.map(x=>{const copy=alertCopy(x);return `<article class="inbox-item ${x.status==='UNREAD'?'unread':''} ${x.severity==='CRITICAL'?'critical':'projected'}"><span class="inbox-icon">${x.severity==='CRITICAL'?'!':'↗'}</span><div><div><span class="severity">${t(x.severity==='CRITICAL'?'critical':'warning')}</span><small>${new Date(x.triggered_at).toLocaleString(locale())}</small></div><h3>${esc(displayCategoryName(category(x.category_id)))}</h3><p>${esc(copy.explanation)}</p><div class="suggestion"><b>${t('suggested_action')}</b><span>${esc(copy.action)}</span></div><footer><button data-alert-status="READ" data-alert-id="${x.id}">${t('understood')}</button><button class="dismiss" data-alert-status="DISMISSED" data-alert-id="${x.id}">${t('dismiss')}</button></footer></div></article>`}).join(''):empty(t('no_alerts'),t('all_under_control'))}
async function loadStatisticsBreakdown(){
  const selectedMonth=state.statisticsMonth,selectedPeriod=state.statisticsBreakdownPeriod,range=statisticsDateRange(selectedMonth,selectedPeriod);
  if(!range)return false;
  const requestId=++state.statisticsBreakdownRequest;
  let breakdownData;
  try{breakdownData=await api(`/statistics/breakdown?date_from=${range.dateFrom}&date_to=${range.dateTo}`)}catch(error){if(requestId!==state.statisticsBreakdownRequest||selectedMonth!==state.statisticsMonth||selectedPeriod!==state.statisticsBreakdownPeriod)return false;throw error}
  if(requestId!==state.statisticsBreakdownRequest||selectedMonth!==state.statisticsMonth||selectedPeriod!==state.statisticsBreakdownPeriod)return false;
  const breakdownItems=(Array.isArray(breakdownData.items)?breakdownData.items:[])
    .map(item=>({category:item.category,amount:Math.max(0,finiteNumber(item.amount))}))
    .filter(item=>item.amount>0)
    .sort((left,right)=>right.amount-left.amount);
  const calculatedTotal=breakdownItems.reduce((sum,item)=>sum+item.amount,0),total=Math.max(0,finiteNumber(breakdownData.total_expense??calculatedTotal));
  const visibleItems=breakdownItems.length>5
    ? [...breakdownItems.slice(0,4),{category:t('other'),amount:breakdownItems.slice(4).reduce((sum,item)=>sum+item.amount,0)}]
    : breakdownItems.slice(0,5);
  $('#statistics-month-label').textContent=range.label;
  $('#statistics-total').textContent=money(total);
  const donut=$('.donut');
  donut.querySelector('b').textContent=new Intl.NumberFormat(locale(),{maximumFractionDigits:0}).format(total);
  donut.querySelector('small').textContent=`₫ · ${$('#statistics-breakdown-period').selectedOptions[0].textContent}`;
  donut.title=money(total);
  donut.setAttribute('aria-label',`${t('total_expense')}: ${money(total)} — ${range.label}`);
  let cursor=0;
  const segments=visibleItems.map((item,index)=>{
    const percentage=total?item.amount/total*100:0,offset=-cursor;
    cursor+=percentage;
    return `<circle class="donut-segment c${index+1}" cx="21" cy="21" r="15.9155" pathLength="100" stroke-dasharray="${percentage.toFixed(4)} ${(100-percentage).toFixed(4)}" stroke-dashoffset="${offset.toFixed(4)}"></circle>`;
  }).join('');
  $('.donut-chart').innerHTML=`<circle class="donut-base" cx="21" cy="21" r="15.9155"></circle>${segments}`;
  const percentageFormatter=new Intl.NumberFormat(locale(),{minimumFractionDigits:1,maximumFractionDigits:1});
  $('.donut-wrap ul').innerHTML=visibleItems.length?visibleItems.map((item,index)=>{
    const percentage=total?item.amount/total*100:0;
    return `<li><i class="c${index+1}"></i><span>${esc(displayCategoryText(item.category))}</span><b>${percentageFormatter.format(percentage)}%</b></li>`;
  }).join(''):`<li class="statistics-empty">${t('no_spending_data')}</li>`;
  state.statisticsRenderedMonth=selectedMonth;
  state.statisticsRenderedPeriod=selectedPeriod;
  return true;
}
async function loadStatisticsTrend(){
  const through=localMonthValue(),requestId=++state.statisticsTrendRequest;
  let trendData;
  try{trendData=await api(`/statistics/trend?through=${through}`)}catch(error){if(requestId!==state.statisticsTrendRequest)return false;throw error}
  if(requestId!==state.statisticsTrendRequest)return false;
  state.statisticsTrendThrough=through;
  state.statisticsTrend=(Array.isArray(trendData.items)?trendData.items:[]).map(item=>({month:String(item.month||''),income:Math.max(0,finiteNumber(item.income)),expense:Math.max(0,finiteNumber(item.expense))}));
  renderTrend();
  return true;
}
async function loadStatistics(){await Promise.all([loadStatisticsBreakdown(),loadStatisticsTrend()])}
function niceAxisStep(value){
  const magnitude=10**Math.floor(Math.log10(value)),normalized=value/magnitude;
  return (normalized<=1?1:normalized<=2?2:normalized<=5?5:10)*magnitude;
}
function renderTrend(){
  const periodSelect=$('#statistics-period'),period=periodSelect.value==='6'?6:12,items=state.statisticsTrend.slice(-period),chart=$('.trend-chart');
  if(periodSelect.value!==String(period))periodSelect.value=String(period);
  const maximum=Math.max(0,...items.flatMap(item=>[item.income,item.expense]));
  const step=maximum>0?niceAxisStep(maximum/4):0,scaleMaximum=step*4||1;
  const points=key=>items.map((item,index)=>`${items.length===1?350:index*(700/(items.length-1))},${210-item[key]/scaleMaximum*180}`).join(' ');
  $('.income-line').setAttribute('points',points('income'));
  $('.expense-line').setAttribute('points',points('expense'));
  const axisFormatter=new Intl.NumberFormat(locale(),{notation:'compact',maximumFractionDigits:1});
  $('.y-labels').innerHTML=Array.from({length:5},(_,index)=>`<span>${step?axisFormatter.format(scaleMaximum-step*index):'0'}</span>`).join('');
  $('.x-labels').innerHTML=items.map(item=>{
    const match=/^(\d{4})-(\d{2})$/.exec(item.month);
    const label=match?new Intl.DateTimeFormat(locale(),{month:'short'}).format(new Date(Number(match[1]),Number(match[2])-1,1)):item.month;
    return `<span>${esc(label)}</span>`;
  }).join('');
  chart.setAttribute('aria-label',t('trend_chart_aria',{count:period,month:formatStatisticsMonth(state.statisticsTrendThrough)}));
}
const accountRow=(x,archived=false)=>`<div class="account-item ${archived?'archived':''}"><span class="metric-icon ${x.type==='BANK'?'blue':'mint'}">${x.type==='BANK'?'▣':'●'}</span><div><b>${esc(accountName(x))}</b><small>${t(x.type==='BANK'?'bank':'cash')} · ${money(x.opening_balance)}</small></div><button type="button" ${archived?`data-restore-account="${x.id}"`:`data-archive-account="${x.id}"`}>${t(archived?'restore':'archive')}</button></div>`;
function renderAccounts(){const hasArchived=state.archivedAccounts.length>0;$('#account-list').innerHTML=state.accounts.length?state.accounts.map(x=>accountRow(x)).join(''):empty(t(hasArchived?'no_active_accounts':'no_accounts'),t(hasArchived?'restore_account_hint':'add_wallet_hint'));$('#archived-accounts').classList.toggle('hidden',!hasArchived);$('#archived-account-heading').textContent=t('archived_accounts',{count:state.archivedAccounts.length});$('#archived-account-list').innerHTML=state.archivedAccounts.map(x=>accountRow(x,true)).join('')}
function confirmAccountDeletion(){const dialog=$('#delete-account-dialog');$('#delete-account-message').textContent=t('archive_confirm');dialog.returnValue='cancel';dialog.showModal();return new Promise(resolve=>dialog.addEventListener('close',()=>resolve(dialog.returnValue==='confirm'),{once:true}))}
function navigate(id){const target=document.getElementById(id)||$('#dashboard'),titles={dashboard:['dashboard','personal_finance'],transactions:['transactions','ledger'],import:['import_statement','safe_import'],budgets:['budgets','month_plan'],alerts:['alerts','finance_assistant'],statistics:['statistics','spending_analysis']},labels=titles[target.id]||titles.dashboard;$$('.view').forEach(v=>v.classList.toggle('active',v===target));$$('.nav-item').forEach(l=>l.classList.toggle('active',l.dataset.view===target.id));$('#page-title').textContent=t(labels[0]);$('#page-kicker').textContent=t(labels[1]);$('.sidebar').classList.remove('open');window.scrollTo({top:0});if(location.hash!==`#${target.id}`)history.pushState(null,'',`#${target.id}`)}
document.addEventListener('click',async e=>{const preferences=$('.profile-preferences'),more=e.target.closest('.profile-more');if(more){const opening=preferences.classList.contains('hidden');preferences.classList.toggle('hidden',!opening);more.setAttribute('aria-expanded',String(opening));return}if(!e.target.closest('.profile-mini')&&!preferences.classList.contains('hidden')){preferences.classList.add('hidden');$('.profile-more').setAttribute('aria-expanded','false')}if(e.target.closest('[data-theme-choice],[data-language]')&&e.target.closest('.profile-preferences')){preferences.classList.add('hidden');$('.profile-more').setAttribute('aria-expanded','false')}const go=e.target.closest('[data-go],[data-view]');if(go){e.preventDefault();navigate(go.dataset.go||go.dataset.view);return}if(e.target.closest('.menu-toggle')){$('.sidebar').classList.toggle('open');return}if(e.target.closest('[data-action="add-transaction"]')){if(!state.accounts.length)return toast(t('need_account'),t('add_account_first'));$('[name="date"]',$('#transaction-form')).value=new Date().toISOString().slice(0,10);$('#transaction-modal').showModal();return}if(e.target.closest('[data-action="accounts"]')){$('#accounts-modal').showModal();return}const del=e.target.closest('[data-delete-transaction]');if(del&&confirm(t('delete_transaction_confirm'))){try{await api(`/transactions/${del.dataset.deleteTransaction}`,{method:'DELETE'});await refreshCore();toast(t('deleted_transaction'))}catch(x){toast(t('delete_failed'),x.message)}return}const page=e.target.closest('[data-page]');if(page){loadTransactions(Number(page.dataset.page));return}const status=e.target.closest('[data-alert-status]');if(status){await api(`/alerts/${status.dataset.alertId}`,{method:'PATCH',body:JSON.stringify({status:status.dataset.alertStatus})});await loadAlerts();return}const filter=e.target.closest('[data-alert-filter]');if(filter){$$('[data-alert-filter]').forEach(x=>x.classList.remove('active'));filter.classList.add('active');loadAlerts(filter.dataset.alertFilter);return}const edit=e.target.closest('[data-edit-budget]');if(edit)setBudget(Number(edit.dataset.editBudget))});
document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;const preferences=$('.profile-preferences');if(!preferences.classList.contains('hidden')){preferences.classList.add('hidden');$('.profile-more').setAttribute('aria-expanded','false');$('.profile-more').focus()}});
$$('[data-auth]').forEach(b=>b.addEventListener('click',()=>showAuth(b.dataset.auth)));
$$('[data-close-dialog]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,b=$('[type="submit"]',f);formError(f);busy(b,true);try{await getCsrf();await api('/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(f)))});await getCsrf();await bootstrap()}catch(x){formError(f,x.message)}finally{busy(b,false)}});
$('#register-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,b=$('[type="submit"]',f),d=Object.fromEntries(new FormData(f));d.consent=$('[name="consent"]',f).checked;formError(f);busy(b,true);try{await getCsrf();await api('/auth/register',{method:'POST',body:JSON.stringify(d)});await api('/auth/login',{method:'POST',body:JSON.stringify({email:d.email,password:d.password})});await getCsrf();await bootstrap()}catch(x){formError(f,x.message)}finally{busy(b,false)}});
$('#transaction-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f)),b=$('#save-transaction');d.amount=String(d.amount).replace(/\D/g,'');busy(b,true);try{await api('/transactions',{method:'POST',body:JSON.stringify(d)});f.reset();$('#transaction-modal').close();await refreshCore();toast(t('saved_transaction'))}catch(x){toast(t('save_failed'),x.message)}finally{busy(b,false)}});
$('#account-form [name="type"]').addEventListener('change',e=>$$('.bank-only').forEach(x=>x.classList.toggle('hidden',e.target.value!=='BANK')));
$('#account-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f)),b=$('#save-account');d.opening_balance=String(d.opening_balance).replace(/\D/g,'');if(d.type==='CASH'){delete d.last_four;delete d.bank_code}busy(b,true);try{await api('/accounts',{method:'POST',body:JSON.stringify(d)});f.reset();await loadAccounts();populateSelects();toast(t('saved_account'))}catch(x){formError(f,x.message)}finally{busy(b,false)}});
$('#account-list').addEventListener('click',async e=>{const b=e.target.closest('[data-archive-account]');if(!b||!await confirmAccountDeletion())return;const id=Number(b.dataset.archiveAccount);b.disabled=true;try{await api(`/accounts/${id}`,{method:'DELETE'});await loadAccounts();populateSelects();toast(t('archived_account'))}catch(x){toast(t('archive_failed'),x.message)}finally{if(b.isConnected)b.disabled=false}});
$('#archived-account-list').addEventListener('click',async e=>{const b=e.target.closest('[data-restore-account]');if(!b)return;try{await api(`/accounts/${b.dataset.restoreAccount}/restore`,{method:'POST'});await loadAccounts();populateSelects();toast(t('restored_account'))}catch(x){toast(t('restore_failed'),x.message)}});
['#transaction-account','#transaction-direction','#transaction-month'].forEach(s=>$(s).addEventListener('change',()=>loadTransactions()));$('#refresh-transactions').addEventListener('click',()=>loadTransactions());$('#transaction-search').addEventListener('input',()=>renderTransactions({items:state.transactions,total:state.transactions.length,page:1,pages:1}));
const file=$('#statement-file'),drop=$('#dropzone');file.addEventListener('change',()=>{if(!file.files.length)return;$('b',drop).textContent=file.files[0].name;$('p',drop).textContent=`${(file.files[0].size/1024).toFixed(1)} KB · ${t('ready')}`;$('#preview-import').disabled=!$('#import-account').value||!$('#import-template').value});['dragenter','dragover'].forEach(type=>drop.addEventListener(type,e=>{e.preventDefault();drop.classList.add('dragging')}));['dragleave','drop'].forEach(type=>drop.addEventListener(type,e=>{e.preventDefault();drop.classList.remove('dragging')}));drop.addEventListener('drop',e=>{if(e.dataTransfer.files.length){file.files=e.dataTransfer.files;file.dispatchEvent(new Event('change'))}});
$('#preview-import').addEventListener('click',async()=>{const b=$('#preview-import'),body=new FormData();body.append('file',file.files[0]);body.append('account_id',$('#import-account').value);body.append('template_id',$('#import-template').value);busy(b,true,t('analyzing'));try{state.importPreview=await api('/imports/preview',{method:'POST',body});renderImportPreview()}catch(x){toast(t('read_statement_failed'),x.message)}finally{busy(b,false)}});
function renderImportPreview(){const p=state.importPreview,probable=p.conflicts||p.sample.filter(x=>x.probable_duplicate_id),box=$('#import-preview');box.classList.remove('hidden');box.innerHTML=`<div class="panel-head"><div><p class="eyebrow">${t('preview_result')}</p><h2>${t('rows_analyzed',{count:p.new+p.duplicate+p.error})}</h2></div><span class="pill positive">${t('unsaved_data')}</span></div><div class="preview-stats"><div><strong>${p.new}</strong><span>${t('new_transactions')}</span></div><div class="warn"><strong>${p.probable_duplicate}</strong><span>${t('possible_duplicates')}</span></div><div class="bad"><strong>${p.error}</strong><span>${t('error_rows')}</span></div></div>${probable.length?`<div class="decision-list">${probable.map(r=>`<label>${t('import_row',{row:r.row_number})} ${esc(r.description)} — ${money(r.amount)}<select data-decision="${r.row_number}"><option value="KEEP">${t('keep_both')}</option><option value="MERGE">${t('skip_import_row')}</option></select></label>`).join('')}</div>`:''}<div class="import-actions">${p.error?`<a class="secondary-btn" href="/imports/${p.batch_id}/errors.csv">${t('download_error_report')}</a>`:''}<button class="primary-btn" id="confirm-import">${t('confirm_import',{count:p.new})}</button></div>`;$('#confirm-import').addEventListener('click',confirmImport);box.scrollIntoView({behavior:'smooth'})}
async function confirmImport(){const decisions={};$$('[data-decision]').forEach(x=>decisions[x.dataset.decision]=x.value);const b=$('#confirm-import');busy(b,true);try{const d=await api(`/imports/${state.importPreview.batch_id}/confirm`,{method:'POST',body:JSON.stringify({decisions,category_overrides:{}})});toast(t('import_success'),t('imported_count',{count:d.imported}));state.importPreview=null;$('#import-preview').classList.add('hidden');file.value='';await refreshCore()}catch(x){toast(t('confirm_failed'),x.message)}finally{busy(b,false)}}
function renderBudgetDialogLanguage(){const form=$('#budget-form'),select=form.elements.category_id,selected=select.value;select.innerHTML=state.categories.map(item=>`<option value="${item.id}">${esc(displayCategoryName(item))}</option>`).join('');if(selected&&[...select.options].some(option=>option.value===selected))select.value=selected;$('#budget-dialog-month').textContent=formatStatisticsMonth(state.month)}
function setBudget(categoryId){const form=$('#budget-form');form.reset();formError(form);renderBudgetDialogLanguage();if(categoryId)form.elements.category_id.value=String(categoryId);$('#budget-dialog').showModal()}
$('#budget-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,data=Object.fromEntries(new FormData(form)),button=$('#save-budget'),amount=String(data.amount).trim();if(!/^\d+$/.test(amount)){formError(form,t('budget_update_failed'));return}data.category_id=Number(data.category_id);data.amount=amount;data.month=state.month;button.disabled=true;button.setAttribute('aria-busy','true');try{await api('/budgets',{method:'PUT',body:JSON.stringify(data)});$('#budget-dialog').close();await Promise.all([loadBudgets(),loadDashboard()]);toast(t('budget_updated'))}catch(error){formError(form,error.message);toast(t('budget_update_failed'),error.message)}finally{button.disabled=false;button.removeAttribute('aria-busy')}});
$$('[data-action="budget"]').forEach(x=>x.addEventListener('click',()=>setBudget()));$$('[data-action="toast"]').forEach(x=>x.addEventListener('click',async()=>{try{const d=await api('/budgets/copy',{method:'POST',body:JSON.stringify({month:state.month})});await Promise.all([loadBudgets(),loadDashboard()]);toast(t('copied_budget'),t('copied_categories',{count:d.copied}))}catch(e){toast(t('copy_failed'),e.message)}}));
$('#mark-all').addEventListener('click',async()=>{await Promise.all(state.alerts.filter(x=>x.status==='UNREAD').map(x=>api(`/alerts/${x.id}`,{method:'PATCH',body:JSON.stringify({status:'READ'})})));await loadAlerts();toast(t('all_alerts_read'))});
$('#logout').addEventListener('click',async()=>{try{await api('/auth/logout',{method:'POST'});state.csrf='';state.profile=null;$('#accounts-modal').close();showAuth()}catch(e){toast(t('logout_failed'),e.message)}});
async function refreshCore(){await Promise.all([loadTransactions(),loadDashboard(),loadBudgets(),loadAlerts(),loadStatistics()])}
$('#statistics-period').addEventListener('change',renderTrend);
function restoreStatisticsBreakdownSelection(){$('#statistics-month-filter').value=state.statisticsRenderedMonth;$('#statistics-breakdown-period').value=String(state.statisticsRenderedPeriod);state.statisticsMonth=state.statisticsRenderedMonth;state.statisticsBreakdownPeriod=state.statisticsRenderedPeriod}
$('#statistics-breakdown-period').addEventListener('change',async event=>{const select=event.currentTarget,next=Number(select.value);if(![1,3,6,12].includes(next)){restoreStatisticsBreakdownSelection();return}state.statisticsBreakdownPeriod=next;try{await loadStatisticsBreakdown()}catch(error){if(state.statisticsBreakdownPeriod===next){restoreStatisticsBreakdownSelection();toast(t('statistics_load_failed'),error.message)}}});
$('#statistics-month-filter').addEventListener('change',async event=>{const input=event.currentTarget,next=input.value;if(!statisticsMonthPattern.test(next)){restoreStatisticsBreakdownSelection();toast(t('invalid_statistics_month'));return}state.statisticsMonth=next;try{await loadStatisticsBreakdown()}catch(error){if(state.statisticsMonth===next){restoreStatisticsBreakdownSelection();toast(t('statistics_load_failed'),error.message)}}});
window.addEventListener('languagechange',async()=>{navigate(location.hash.slice(1)||'dashboard');populateSelects();renderAccounts();if($('#budget-dialog').open)renderBudgetDialogLanguage();if(state.profile)$('.welcome-row h1').innerHTML=`${esc(t('greeting_named',{name:state.profile.full_name}))} <span>👋</span>`;if(file.files.length)file.dispatchEvent(new Event('change'));if(state.importPreview)renderImportPreview();if(state.profile)await Promise.all([loadDashboard(),loadTransactions(),loadBudgets(),loadAlerts(),loadStatistics(),loadTemplates()])});
window.addEventListener('popstate',()=>navigate(location.hash.slice(1)||'dashboard'));$('#transaction-month').value=state.month;$('#statistics-month-filter').value=state.statisticsMonth;$('#statistics-breakdown-period').value=String(state.statisticsBreakdownPeriod);navigate(location.hash.slice(1)||'dashboard');bootstrap();
