const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={csrf:'',profile:null,accounts:[],categories:[],transactions:[],alerts:[],month:new Date().toISOString().slice(0,7),importPreview:null};
const money=v=>`${new Intl.NumberFormat('vi-VN').format(Number(v||0))} ₫`,dateVi=v=>v?new Intl.DateTimeFormat('vi-VN').format(new Date(`${v.slice(0,10)}T00:00:00`)):'—';
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const category=id=>state.categories.find(x=>x.id===Number(id)),account=id=>state.accounts.find(x=>x.id===Number(id));
const accountName=x=>x?`${x.name}${x.last_four?` •••• ${x.last_four}`:''}`:'Tài khoản';
class ApiError extends Error{constructor(message,status){super(message);this.status=status}}
async function getCsrf(){const r=await fetch('/auth/csrf',{credentials:'same-origin'}),d=await r.json();state.csrf=d.csrf_token}
async function api(path,options={}){const method=options.method||'GET';if(method!=='GET'&&!state.csrf)await getCsrf();const headers=new Headers(options.headers||{});if(method!=='GET')headers.set('X-CSRFToken',state.csrf);if(options.body&&!(options.body instanceof FormData))headers.set('Content-Type','application/json');const r=await fetch(path,{...options,method,headers,credentials:'same-origin'});if(r.status===401){showAuth();throw new ApiError('Phiên đăng nhập đã hết hạn.',401)}const type=r.headers.get('content-type')||'',data=type.includes('json')?await r.json():await r.blob();if(!r.ok)throw new ApiError(data?.error||`Yêu cầu thất bại (${r.status})`,r.status);return data}
function showAuth(mode='login'){$('#auth-screen').classList.remove('hidden');$('#app-shell').classList.add('hidden');$('#login-form').classList.toggle('hidden',mode!=='login');$('#register-form').classList.toggle('hidden',mode!=='register')}
function showApp(){$('#auth-screen').classList.add('hidden');$('#app-shell').classList.remove('hidden')}
function toast(title,detail=''){const t=$('#toast');$('b',t).textContent=title;$('small',t).textContent=detail;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),3000)}
function busy(b,on,label='Đang xử lý...'){if(!b)return;if(!b.dataset.label)b.dataset.label=b.textContent;b.disabled=on;b.textContent=on?label:b.dataset.label}
function formError(f,e=''){$('.form-error',f).textContent=e}
async function bootstrap(){try{state.profile=await api('/profile');showApp();$('.profile-mini b').textContent=state.profile.full_name;$('.profile-mini small').textContent=state.profile.email.replace(/^(.{2}).*(@.*)$/,'$1***$2');await Promise.all([loadAccounts(),loadCategories()]);populateSelects();await Promise.all([loadDashboard(),loadTransactions(),loadBudgets(),loadAlerts(),loadStatistics(),loadTemplates()])}catch(e){if(e.status!==401)toast('Không thể khởi tạo ứng dụng',e.message)}}
async function loadAccounts(){state.accounts=(await api('/accounts')).items.filter(x=>!x.archived);renderAccounts()}
async function loadCategories(){state.categories=(await api('/categories')).items.filter(x=>x.nature)}
async function loadTemplates(){const items=(await api('/imports/templates')).items;$('#import-template').innerHTML=items.length?items.map(x=>`<option value="${x.id}">${esc(x.bank_code)} — ${esc(x.name)}</option>`).join(''):'<option value="">Chưa có mẫu nhập</option>'}
function populateSelects(){const opts=state.accounts.map(x=>`<option value="${x.id}">${esc(accountName(x))}</option>`).join('');$('#transaction-account').innerHTML=`<option value="">Tất cả tài khoản</option>${opts}`;$('#import-account').innerHTML=opts||'<option value="">Hãy tạo tài khoản trước</option>';$('[name="account_id"]',$('#transaction-form')).innerHTML=opts;$('[name="category_id"]',$('#transaction-form')).innerHTML=state.categories.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}
async function loadDashboard(){const d=await api(`/statistics/dashboard?month=${state.month}`),metrics=[['↗','mint','Thu nhập tháng này',money(d.income),'Các khoản thu đã ghi nhận'],['↘','coral','Chi tiêu tháng này',money(d.expense),'Các khoản chi đã ghi nhận'],['◇','blue','An toàn để chi tiêu',money(d.safe_to_spend),'Sau khoản chi cam kết'],['◎','violet','Chênh lệch thu chi',money(d.net),d.net>=0?'Dòng tiền dương':'Dòng tiền âm']];$('#dashboard-metrics').innerHTML=metrics.map((x,i)=>`<article class="metric-card ${i===0?'accent':''}"><div class="metric-head"><span class="metric-icon ${x[1]}">${x[0]}</span></div><p>${x[2]}</p><strong>${x[3]}</strong><small>${x[4]}</small></article>`).join('');$('#dashboard-budgets').innerHTML=budgetRows(d.budget_progress)}
function budgetRows(items){return items.length?items.map(x=>{const t=x.status==='RED'?'danger':x.status==='AMBER'?'warning':'good';return `<div class="budget-row"><span class="cat-icon ${t==='danger'?'shop':t==='warning'?'food':'travel'}">${esc(x.category[0])}</span><div><b>${esc(x.category)}</b><small>${money(x.spent)} / ${money(x.budget)}</small><div class="progress"><i class="${t}" style="width:${Math.min(x.percent,100)}%"></i></div></div><strong class="status ${t}-text">${x.percent}%<small>${esc(x.label)}</small></strong></div>`}).join(''):empty('Chưa có ngân sách tháng này','Hãy thiết lập hạn mức để theo dõi tiến độ.')}
const empty=(title,text)=>`<div class="empty-state"><b>${title}</b><span>${text}</span></div>`;
async function loadTransactions(page=1){const month=$('#transaction-month').value||state.month,[y,m]=month.split('-').map(Number),last=new Date(y,m,0).getDate(),p=new URLSearchParams({page,per_page:20,date_from:`${month}-01`,date_to:`${month}-${last}`});if($('#transaction-account').value)p.set('account_id',$('#transaction-account').value);if($('#transaction-direction').value)p.set('direction',$('#transaction-direction').value);const d=await api(`/transactions?${p}`);state.transactions=d.items;renderTransactions(d);$('#recent-transactions').innerHTML=transactionRows(d.items.slice(0,5),false)}
function transactionRows(items,controls=true){return items.length?items.map(x=>`<tr>${controls?'<td><input type="checkbox"></td>':''}<td><span class="merchant-logo ${x.direction==='IN'?'green':''}">${x.direction==='IN'?'↗':'↘'}</span><b>${esc(x.description||'Không có mô tả')}</b></td><td><span class="tag">${esc(category(x.category_id)?.name||'Chưa phân loại')}</span></td><td>${esc(accountName(account(x.account_id)))}</td><td>${dateVi(x.date)}</td><td class="amount ${x.direction==='IN'?'in':'out'}">${x.direction==='IN'?'+':'−'} ${money(x.amount)}</td>${controls?`<td><button class="row-menu" data-delete-transaction="${x.id}">×</button></td>`:''}</tr>`).join(''):`<tr><td colspan="${controls?7:5}">${empty('Chưa có giao dịch','Thêm giao dịch đầu tiên để bắt đầu.')}</td></tr>`}
function renderTransactions(d){const q=$('#transaction-search').value.toLowerCase(),items=d.items.filter(x=>(x.description||'').toLowerCase().includes(q));$('#transaction-rows').innerHTML=transactionRows(items);$('.pagination>span').textContent=`${d.total} giao dịch · Trang ${d.page}/${Math.max(d.pages,1)}`;$('.pagination>div').innerHTML=`<button data-page="${Math.max(1,d.page-1)}" ${d.page<=1?'disabled':''}>‹</button><button class="active">${d.page}</button><button data-page="${Math.min(d.pages,d.page+1)}" ${d.page>=d.pages?'disabled':''}>›</button>`}
async function loadBudgets(){const [b,d]=await Promise.all([api(`/budgets?month=${state.month}`),api(`/statistics/dashboard?month=${state.month}`)]),total=b.items.reduce((s,x)=>s+x.amount,0),spent=d.expense,summary=$$('.budget-summary>div:not(.ring) strong');summary[0].textContent=money(total);summary[1].textContent=money(spent);summary[2].textContent=money(total-spent);const pct=total?Math.round(spent/total*100):0;$('.ring').style.setProperty('--value',Math.min(pct,100));$('.ring b').textContent=`${pct}%`;const progress=Object.fromEntries(d.budget_progress.map(x=>[x.category_id,x]));$('#budget-cards').innerHTML=b.items.length?b.items.map(x=>{const c=category(x.category_id),p=progress[x.category_id]||{spent:0,percent:0,status:'GREEN',label:'Trong kế hoạch'},t=p.status==='RED'?'danger':p.status==='AMBER'?'warning':'good';return `<article class="category-card ${t==='danger'?'danger-border':''}"><div><span class="cat-icon food">${esc((c?.name||'?')[0])}</span><span><b>${esc(c?.name||'Danh mục')}</b><small>${natureLabel(c?.nature)}</small></span><button data-edit-budget="${x.category_id}">✎</button></div><strong>${money(p.spent)} <small>/ ${money(x.amount)}</small></strong><div class="progress large"><i class="${t}" style="width:${Math.min(p.percent,100)}%"></i></div><p><span class="${t}-text">${esc(p.label)}</span><span>${p.percent}%</span></p></article>`}).join(''):empty('Chưa thiết lập ngân sách','Nhấn “Thêm ngân sách” để bắt đầu.')}
const natureLabel=n=>({COMMITTED:'Chi phí cam kết',SEMI_FIXED:'Chi phí bán cố định',DISCRETIONARY:'Chi tiêu linh hoạt'}[n]||'Danh mục');
async function loadAlerts(filter='ALL'){state.alerts=(await api('/alerts')).items;const unread=state.alerts.filter(x=>x.status==='UNREAD').length;$('#alert-total').textContent=state.alerts.length;$('#alert-unread').textContent=unread;$('.nav-badge').textContent=unread;$('.nav-badge').classList.toggle('hidden',!unread);const items=filter==='ALL'?state.alerts:state.alerts.filter(x=>x.status===filter);$('#alert-inbox').innerHTML=items.length?items.map(x=>`<article class="inbox-item ${x.status==='UNREAD'?'unread':''} ${x.severity==='CRITICAL'?'critical':'projected'}"><span class="inbox-icon">${x.severity==='CRITICAL'?'!':'↗'}</span><div><div><span class="severity">${x.severity==='CRITICAL'?'NGHIÊM TRỌNG':'CẢNH BÁO'}</span><small>${new Date(x.triggered_at).toLocaleString('vi-VN')}</small></div><h3>${esc(category(x.category_id)?.name||'Cảnh báo chi tiêu')}</h3><p>${esc(x.explanation)}</p><div class="suggestion"><b>Gợi ý hành động</b><span>${esc(x.suggested_action)}</span></div><footer><button data-alert-status="READ" data-alert-id="${x.id}">Đã hiểu</button><button class="dismiss" data-alert-status="DISMISSED" data-alert-id="${x.id}">Bỏ qua</button></footer></div></article>`).join(''):empty('Không có cảnh báo','Mọi thứ đang trong tầm kiểm soát.')}
async function loadStatistics(){const [y,m]=state.month.split('-').map(Number),last=new Date(y,m,0).getDate(),[b,t]=await Promise.all([api(`/statistics/breakdown?date_from=${state.month}-01&date_to=${state.month}-${last}`),api(`/statistics/trend?through=${state.month}`)]),total=b.items.reduce((s,x)=>s+x.amount,0),colors=['#4779b9','#df9a42','#a86caa','#3fa486','#d6dfda'];$('.donut b').textContent=new Intl.NumberFormat('vi-VN',{notation:'compact',maximumFractionDigits:1}).format(total);let cursor=0,stops=[];$('.donut-wrap ul').innerHTML=b.items.length?b.items.slice(0,5).map((x,i)=>{const pct=total?x.amount/total*100:0;stops.push(`${colors[i]} ${cursor}% ${cursor+pct}%`);cursor+=pct;return `<li><i style="background:${colors[i]}"></i><span>${esc(x.category)}</span><b>${pct.toFixed(1)}%</b></li>`}).join(''):'<li>Chưa có dữ liệu chi tiêu</li>';$('.donut').style.background=stops.length?`conic-gradient(${stops.join(',')})`:'#edf1ef';renderTrend(t.items)}
function renderTrend(items){const max=Math.max(...items.flatMap(x=>[x.income,x.expense]),1),points=k=>items.map((x,i)=>`${i*(700/(items.length-1||1))},${210-x[k]/max*180}`).join(' ');$('.income-line').setAttribute('points',points('income'));$('.expense-line').setAttribute('points',points('expense'));$('.x-labels').innerHTML=items.map(x=>`<span>T${Number(x.month.slice(5))}</span>`).join('')}
function renderAccounts(){$('#account-list').innerHTML=state.accounts.length?state.accounts.map(x=>`<div class="account-item"><span class="metric-icon ${x.type==='BANK'?'blue':'mint'}">${x.type==='BANK'?'▣':'●'}</span><div><b>${esc(accountName(x))}</b><small>${x.type==='BANK'?'Ngân hàng':'Tiền mặt'} · ${money(x.opening_balance)}</small></div><button data-archive-account="${x.id}">Lưu trữ</button></div>`).join(''):empty('Chưa có tài khoản','Thêm ví hoặc tài khoản ngân hàng để ghi giao dịch.')}
function navigate(id){const target=document.getElementById(id)||$('#dashboard');$$('.view').forEach(v=>v.classList.toggle('active',v===target));$$('.nav-item').forEach(l=>l.classList.toggle('active',l.dataset.view===target.id));$('#page-title').textContent=target.dataset.title;$('#page-kicker').textContent=target.dataset.kicker;$('.sidebar').classList.remove('open');window.scrollTo({top:0});if(location.hash!==`#${target.id}`)history.pushState(null,'',`#${target.id}`)}
document.addEventListener('click',async e=>{const go=e.target.closest('[data-go],[data-view]');if(go){e.preventDefault();navigate(go.dataset.go||go.dataset.view);return}if(e.target.closest('.menu-toggle')){$('.sidebar').classList.toggle('open');return}if(e.target.closest('[data-action="add-transaction"]')){if(!state.accounts.length)return toast('Cần tạo tài khoản','Thêm một tài khoản trước.');$('[name="date"]',$('#transaction-form')).value=new Date().toISOString().slice(0,10);$('#transaction-modal').showModal();return}if(e.target.closest('[data-action="accounts"]')||e.target.closest('[data-action="profile"]')){$('#accounts-modal').showModal();return}const del=e.target.closest('[data-delete-transaction]');if(del&&confirm('Xóa giao dịch này?')){try{await api(`/transactions/${del.dataset.deleteTransaction}`,{method:'DELETE'});await refreshCore();toast('Đã xóa giao dịch')}catch(x){toast('Không thể xóa',x.message)}return}const page=e.target.closest('[data-page]');if(page){loadTransactions(Number(page.dataset.page));return}const status=e.target.closest('[data-alert-status]');if(status){await api(`/alerts/${status.dataset.alertId}`,{method:'PATCH',body:JSON.stringify({status:status.dataset.alertStatus})});await loadAlerts();return}const filter=e.target.closest('[data-alert-filter]');if(filter){$$('[data-alert-filter]').forEach(x=>x.classList.remove('active'));filter.classList.add('active');loadAlerts(filter.dataset.alertFilter);return}const edit=e.target.closest('[data-edit-budget]');if(edit)setBudget(Number(edit.dataset.editBudget))});
$$('[data-auth]').forEach(b=>b.addEventListener('click',()=>showAuth(b.dataset.auth)));
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,b=$('[type="submit"]',f);formError(f);busy(b,true);try{await getCsrf();await api('/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(f)))});await getCsrf();await bootstrap()}catch(x){formError(f,x.message)}finally{busy(b,false)}});
$('#register-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,b=$('[type="submit"]',f),d=Object.fromEntries(new FormData(f));d.consent=$('[name="consent"]',f).checked;formError(f);busy(b,true);try{await getCsrf();await api('/auth/register',{method:'POST',body:JSON.stringify(d)});await api('/auth/login',{method:'POST',body:JSON.stringify({email:d.email,password:d.password})});await getCsrf();await bootstrap()}catch(x){formError(f,x.message)}finally{busy(b,false)}});
$('#transaction-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f)),b=$('#save-transaction');d.amount=String(d.amount).replace(/\D/g,'');busy(b,true);try{await api('/transactions',{method:'POST',body:JSON.stringify(d)});f.reset();$('#transaction-modal').close();await refreshCore();toast('Đã thêm giao dịch')}catch(x){toast('Không thể lưu',x.message)}finally{busy(b,false)}});
$('#account-form [name="type"]').addEventListener('change',e=>$$('.bank-only').forEach(x=>x.classList.toggle('hidden',e.target.value!=='BANK')));
$('#account-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f)),b=$('#save-account');d.opening_balance=String(d.opening_balance).replace(/\D/g,'');if(d.type==='CASH'){delete d.last_four;delete d.bank_code}busy(b,true);try{await api('/accounts',{method:'POST',body:JSON.stringify(d)});f.reset();await loadAccounts();populateSelects();toast('Đã thêm tài khoản')}catch(x){formError(f,x.message)}finally{busy(b,false)}});
$('#account-list').addEventListener('click',async e=>{const b=e.target.closest('[data-archive-account]');if(!b||!confirm('Lưu trữ tài khoản này?'))return;try{await api(`/accounts/${b.dataset.archiveAccount}`,{method:'DELETE'});await loadAccounts();populateSelects();toast('Đã lưu trữ tài khoản')}catch(x){toast('Không thể lưu trữ',x.message)}});
['#transaction-account','#transaction-direction','#transaction-month'].forEach(s=>$(s).addEventListener('change',()=>loadTransactions()));$('#refresh-transactions').addEventListener('click',()=>loadTransactions());$('#transaction-search').addEventListener('input',()=>renderTransactions({items:state.transactions,total:state.transactions.length,page:1,pages:1}));
const file=$('#statement-file'),drop=$('#dropzone');file.addEventListener('change',()=>{if(!file.files.length)return;$('b',drop).textContent=file.files[0].name;$('p',drop).textContent=`${(file.files[0].size/1024).toFixed(1)} KB · Sẵn sàng`;$('#preview-import').disabled=!$('#import-account').value||!$('#import-template').value});['dragenter','dragover'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.add('dragging')}));['dragleave','drop'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.remove('dragging')}));drop.addEventListener('drop',e=>{if(e.dataTransfer.files.length){file.files=e.dataTransfer.files;file.dispatchEvent(new Event('change'))}});
$('#preview-import').addEventListener('click',async()=>{const b=$('#preview-import'),body=new FormData();body.append('file',file.files[0]);body.append('account_id',$('#import-account').value);body.append('template_id',$('#import-template').value);busy(b,true,'Đang phân tích...');try{state.importPreview=await api('/imports/preview',{method:'POST',body});renderImportPreview()}catch(x){toast('Không thể đọc sao kê',x.message)}finally{busy(b,false)}});
function renderImportPreview(){const p=state.importPreview,probable=p.conflicts||p.sample.filter(x=>x.probable_duplicate_id),box=$('#import-preview');box.classList.remove('hidden');box.innerHTML=`<div class="panel-head"><div><p class="eyebrow">KẾT QUẢ XEM TRƯỚC</p><h2>${p.new+p.duplicate+p.error} dòng đã phân tích</h2></div><span class="pill positive">Chưa lưu dữ liệu</span></div><div class="preview-stats"><div><strong>${p.new}</strong><span>Giao dịch mới</span></div><div class="warn"><strong>${p.probable_duplicate}</strong><span>Có thể trùng</span></div><div class="bad"><strong>${p.error}</strong><span>Dòng lỗi</span></div></div>${probable.length?`<div class="decision-list">${probable.map(r=>`<label>Dòng ${r.row_number}: ${esc(r.description)} — ${money(r.amount)}<select data-decision="${r.row_number}"><option value="KEEP">Giữ cả hai</option><option value="MERGE">Bỏ dòng nhập</option></select></label>`).join('')}</div>`:''}<div class="import-actions">${p.error?`<a class="secondary-btn" href="/imports/${p.batch_id}/errors.csv">Tải báo cáo lỗi</a>`:''}<button class="primary-btn" id="confirm-import">Xác nhận nhập ${p.new} giao dịch</button></div>`;$('#confirm-import').addEventListener('click',confirmImport);box.scrollIntoView({behavior:'smooth'})}
async function confirmImport(){const decisions={};$$('[data-decision]').forEach(x=>decisions[x.dataset.decision]=x.value);const b=$('#confirm-import');busy(b,true);try{const d=await api(`/imports/${state.importPreview.batch_id}/confirm`,{method:'POST',body:JSON.stringify({decisions,category_overrides:{}})});toast('Nhập sao kê thành công',`${d.imported} giao dịch đã được thêm.`);state.importPreview=null;$('#import-preview').classList.add('hidden');file.value='';await refreshCore()}catch(x){toast('Không thể xác nhận',x.message)}finally{busy(b,false)}}
async function setBudget(categoryId){const list=state.categories.map(c=>`${c.id}: ${c.name}`).join('\n'),selected=categoryId||Number(prompt(`Nhập ID danh mục:\n${list}`));if(!selected)return;const amount=prompt('Ngân sách tháng (VND):');if(amount===null)return;try{await api('/budgets',{method:'PUT',body:JSON.stringify({month:state.month,category_id:selected,amount:String(amount).replace(/\D/g,'')})});await Promise.all([loadBudgets(),loadDashboard()]);toast('Đã cập nhật ngân sách')}catch(x){toast('Không thể cập nhật',x.message)}}
$$('[data-action="budget"]').forEach(x=>x.addEventListener('click',()=>setBudget()));$$('[data-action="toast"]').forEach(x=>x.addEventListener('click',async()=>{try{const d=await api('/budgets/copy',{method:'POST',body:JSON.stringify({month:state.month})});await Promise.all([loadBudgets(),loadDashboard()]);toast('Đã sao chép ngân sách',`${d.copied} danh mục được thêm.`)}catch(e){toast('Không thể sao chép',e.message)}}));
$('#mark-all').addEventListener('click',async()=>{await Promise.all(state.alerts.filter(x=>x.status==='UNREAD').map(x=>api(`/alerts/${x.id}`,{method:'PATCH',body:JSON.stringify({status:'READ'})})));await loadAlerts();toast('Đã đọc tất cả cảnh báo')});
$('#logout').addEventListener('click',async()=>{try{await api('/auth/logout',{method:'POST'});state.csrf='';state.profile=null;$('#accounts-modal').close();showAuth()}catch(e){toast('Không thể đăng xuất',e.message)}});
async function refreshCore(){await Promise.all([loadTransactions(),loadDashboard(),loadBudgets(),loadAlerts(),loadStatistics()])}
window.addEventListener('popstate',()=>navigate(location.hash.slice(1)||'dashboard'));$('#transaction-month').value=state.month;navigate(location.hash.slice(1)||'dashboard');bootstrap();
